### ISSUE TITLE
Exported ONNX Model doesn't output matched jet index predictions

### ISSUE THREAD

**Issue by jpgombas** [Alexanders101/SPANet#13]
When predicting assignments through spanet.predict, you get for example "/TARGETS/tR/b" in the output h5 file. This contains the index that spanet predicts a jet to match to the b from "tR". However, when exporting, the ONNX model doesn't have any predicted assignments. It does have the detection and assignment probabilities though. Is there a way to get this prediction through the embeddings, or is this feature currently unavailable?

**Comment by Alexanders101** [comment]
Hello! The network outputs the full joint distributions for the input jets. Converting this joint into a maximal non-conflicting assignment is a somewhat involved process, and one that couldn't be implemented in onnx. For now, the end user should implement the assignment algorithm where they are calling the onnx network from. For reference, our numba-python implementation is available here:
https://github.com/Alexanders101/SPANet/blob/master/spanet/network/prediction_selection.py

**Comment by jpgombas** [comment]
I see, that makes sense. Thank you for the response!
